//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLII_Dejan_Prodanovic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeDBEntities : DbContext
    {
        public EmployeeDBEntities()
            : base("name=EmployeeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblLOCATION> tblLOCATIONs { get; set; }
        public virtual DbSet<tblSector> tblSectors { get; set; }
        public virtual DbSet<vwEmployee> vwEmployees { get; set; }
        public virtual DbSet<vwLOCATION> vwLOCATIONs { get; set; }
        public virtual DbSet<vwMenager> vwMenagers { get; set; }
    }
}
