//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLII_Dejan_Prodanovic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public string Location { get; set; }
        public int EmployeeID { get; set; }
        public int LocationID { get; set; }
        public int SectorID { get; set; }
        public int GenderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MenagerName { get; set; }
        public string JMBG { get; set; }
        public string RegistrationNumber { get; set; }
        public string TelefonNumber { get; set; }
        public string SectorName { get; set; }
        public string Gender { get; set; }
    }
}
